# Generated by Django 3.0.8 on 2020-07-30 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
     
    ]
