# Generated by Django 3.0.8 on 2020-07-02 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkers_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='featured',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
