# Generated by Django 3.0.8 on 2020-07-30 04:31

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkers_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMoves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moves', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
    ]
