# Generated by Django 3.0.8 on 2020-07-27 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkers_app', '0002_user_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMoves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('moves', models.CharField(max_length=120)),
            ],
        ),
    ]
