# Generated by Django 3.0.8 on 2020-07-30 04:49

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checkers_app', '0004_remove_usermoves_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermoves',
            name='moves',
            field=jsonfield.fields.JSONField(default={'hernan': ['1', '1', '0', '2', '2', '1', '0', '2', '0']}),
        ),
    ]
