# Generated by Django 3.0.8 on 2020-07-31 03:23

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checkers_app', '0007_auto_20200730_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermoves',
            name='chance',
            field=models.IntegerField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='usermoves',
            name='moves',
            field=jsonfield.fields.JSONField(default={'hernan': ['1', '1', '0', '2', '2', '1', '0', '2', '0']}),
        ),
    ]
