# Generated by Django 3.0.8 on 2020-07-31 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkers_app', '0008_auto_20200731_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermoves',
            name='chance',
            field=models.IntegerField(default=0),
        ),
    ]
