# Generated by Django 3.0.8 on 2020-07-31 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkers_app', '0009_auto_20200731_0324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermoves',
            name='chance',
        ),
        migrations.AddField(
            model_name='usermoves',
            name='last_move',
            field=models.CharField(default='computer', max_length=50),
        ),
    ]
